server:
  port: 8080
spring:
  application:
    name: "cleanArquitecture"
  devtools:
    add-properties: false
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: "jdbc:postgresql://localhost:5432/pruebas"
    username: postgres
    password: 123456
jwt:
  issuer: Bancolombia
  secret: Millave
logging:
  level:
    co.com.bancolombia: "debug"
    root: "error"
  profiles:
    include: null
